added new scripts

diff --git a/scripts/sessionizer b/scripts/sessionizer
--- a/scripts/sessionizer
+++ b/scripts/sessionizer
@@ -1,94 +1,111 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
-FZF_THEME=$($HOME/.local/bin/scripts/fzf_theme)
+# Define constants
+FZF_THEME="$HOME/.local/bin/scripts/fzf_theme"
+LS_OPTS="-la --color=always"
 
+# List of directories to include in the search
 INCLUDED_DIRS=(
-    # "$HOME/"
-    "$HOME/.dotfiles/"
-    "$HOME/Documents/projects/"
-    "$HOME/.local/bin/"
-    "$HOME/Google Drive/My Drive/"
+    "$HOME/.dotfiles"
+    "$HOME/Documents"
+    "$HOME/.local/bin"
+    "$HOME/Google Drive/My Drive"
 )
 
-# Function to find and process symlinks using xargs
-search_dirs() {
-    local finder=$1
-    local fuzzy_finder="$2"
-    local include_params=()
+# Function to handle cleanup on keyboard interrupt or stop
+cleanup() {
+    echo "Interrupt detected. Cleaning up..."
 
-    for dir in "${INCLUDED_DIRS[@]}"; do
-        include_params+=("$dir")
-    done
-
-    # Use find command to search directories efficiently
-    all_dirs=$(
-        {
-            $finder -H --max-depth 1 --type d . "$HOME"
-            $finder -H --min-depth 1 --max-depth 3 --type d . "${include_params[@]}"
-        } | sort | uniq
-    )
-
-    selected=$(
-        echo "$all_dirs" | $fuzzy_finder $FZF_THEME --cycle --preview 'ls -la {}'
-    )
-}
-
-# search_dirs() {
-#     local finder=$1
-#     local fuzzy_finder="$2"
-#     local include_params=()
-#
-#     for dir in "${INCLUDED_DIRS[@]}"; do
-#         include_params+=("$dir")
-#     done
-#
-#     # Use a single find command with combined parameters
-#     all_dirs=$(find "$HOME" -maxdepth 3 -type d \( $(printf -- '-path %s -o ' "${include_params[@]}" | sed 's/ -o $//') \) -print | sort -u | sed "s|^$HOME|~|")
-#
-#     # Perform fuzzy search
-#     selected=$(echo "$all_dirs" | sed "s|^~|$HOME|" | fzf $FZF_THEME --cycle --preview 'ls -la {}')
-# }
-
-
-# Check if sk is installed and use it if available
-if command -v sk >/dev/null && sk --version >/dev/null 2>&1; then
-    search_dirs "fd" "sk"
-
-# Check if fzf is installed and use it if available
-elif command -v fzf >/dev/null && fzf --version >/dev/null 2>&1; then
-    search_dirs "fd" "fzf"
-
-# If neither sk nor fzf is installed, print a warning and exit
-else
-    echo "Warning: No Fuzzy finder program detected (fzf or sk). Install one or use command line arguments."
-    exit 1
-fi
-
-# Exit if no directory is selected
-if [[ -z $selected ]]; then
-    echo "No directory selected. Exiting."
-    exit 0
-fi
-
-tmux_running=$(pgrep tmux)
-
-# Determine whether to use tmux or WezTerm
-if [[ -n $TMUX ]] && [[ -n $tmux_running ]]; then
-    selected_name=$(basename "$selected" | tr '.' '_')
-    if ! tmux has-session -t=$selected_name 2> /dev/null; then
-        tmux new-session -ds $selected_name -c $selected
-    fi
-
-    tmux switch-client -t $selected_name
-elif command -v wezterm >/dev/null && wezterm --version | grep -q "wezterm"; then
-    # tab_id=$(wezterm cli list | grep "$selected_name" | awk 'FNR == 1 {print $2}')
-    tab_id=$(wezterm cli list | grep -w "file://.*$selected" | awk 'FNR == 1 {print $2}')
-    if [[ -z $tab_id ]]; then
-        wezterm cli spawn --cwd "$selected"
-    else
+    if pgrep -x tmux >/dev/null && [[ -n "$TMUX" ]]; then
+        local original_session
+        original_session=$(tmux list-sessions -F "#{session_name}" | tail -n 1)
+        tmux switch-client -t "$original_session"
+    elif command -v wezterm >/dev/null && wezterm --version | grep -q "wezterm"; then
+        local tab_id
+        tab_id=$(wezterm cli list | tail -n 1 | awk '{print $2}')
         wezterm cli activate-tab --tab-id "$tab_id"
     fi
-else
-    echo "Warning: No terminal multiplexer detected (tmux or WezTerm)."
-fi
 
+    exit 0
+}
+
+# Trap the SIGINT (Ctrl+C) and SIGTSTP (Ctrl+Z) signals to handle cleanup
+trap cleanup SIGINT SIGTSTP
+
+# Function to find and deduplicate directories
+find_directories() {
+    local finder="$1"
+    local include_params=("${@:2}")
+
+    # Use a single call to find directories, optimizing the process
+    "$finder" -H --min-depth 1 --max-depth 3 --type d . "${include_params[@]}" | sort -u
+}
+
+# Function to search and select directories using a fuzzy finder
+search_dirs() {
+    local finder="$1"
+    local fuzzy_finder="$2"
+    local include_params=("${INCLUDED_DIRS[@]}")
+
+    local all_dirs
+    all_dirs=$(find_directories "$finder" "${include_params[@]}")
+
+    local selected
+    selected=$(
+        echo "$all_dirs" | "$fuzzy_finder" "$($FZF_THEME)" --cycle \
+            --preview "if command -v eza >/dev/null; then eza $LS_OPTS --group-directories-first {}; else ls $LS_OPTS {}; fi"
+    )
+
+    if [ -n "$selected" ]; then
+        echo "$selected"
+    else
+        echo "No directory selected. Exiting." >&2
+        return 1
+    fi
+}
+
+# Function to handle terminal multiplexer or tab management
+handle_terminal() {
+    local selected="$1"
+    local selected_name
+
+    if pgrep -x tmux >/dev/null && [[ -n "$TMUX" ]]; then
+        selected_name=$(basename "$selected" | tr '.' '_')
+        if ! tmux has-session -t="$selected_name" 2>/dev/null; then
+            tmux new-session -ds "$selected_name" -c "$selected"
+        fi
+        tmux switch-client -t "$selected_name"
+    elif command -v wezterm >/dev/null && wezterm --version | grep -q "wezterm"; then
+        local tab_id
+        tab_id=$(wezterm cli list | awk -v selected="$selected" 'match($0, "file://.*" selected) {print $2; exit}')
+        if [[ -z $tab_id ]]; then
+            wezterm cli spawn --cwd "$selected"
+        else
+            wezterm cli activate-tab --tab-id "$tab_id"
+        fi
+    else
+        echo "Warning: No terminal multiplexer detected (tmux or WezTerm)." >&2
+        exit 1
+    fi
+}
+
+# Main function to coordinate the script
+main() {
+    local selected
+
+    if command -v sk >/dev/null && sk --version >/dev/null 2>&1; then
+        selected=$(search_dirs "fd" "sk")
+    elif command -v fzf >/dev/null && fzf --version >/dev/null 2>&1; then
+        selected=$(search_dirs "fd" "fzf")
+    else
+        echo "Warning: No fuzzy finder program detected (fzf or sk). Install one or use command line arguments." >&2
+        exit 1
+    fi
+
+    if [[ -n "$selected" ]]; then
+        handle_terminal "$selected"
+    fi
+}
+
+# Execute the main function
+main
diff --git a/scripts/setup_dev_env b/scripts/setup_dev_env
--- a/scripts/setup_dev_env
+++ b/scripts/setup_dev_env
@@ -5,48 +5,114 @@ command_exists() {
     command -v "$1" >/dev/null 2>&1
 }
 
+# Function to perform package manager updates and upgrades
+update_and_upgrade() {
+    local package_manager=$1
+    case $package_manager in
+    "brew")
+        echo "Updating and upgrading Homebrew..."
+        brew update && brew upgrade
+        ;;
+    "apt-get")
+        echo "Updating package list and upgrading..."
+        sudo apt-get update && sudo apt-get upgrade -y
+        ;;
+    "yum")
+        echo "Updating package list and upgrading..."
+        sudo yum check-update && sudo yum update -y
+        ;;
+    *)
+        echo "Unsupported package manager: $package_manager"
+        exit 1
+        ;;
+    esac
+}
+
+# Function to perform cleanup tasks
+cleanup() {
+    local package_manager=$1
+    case $package_manager in
+    "brew")
+        echo "Cleaning up..."
+        brew cleanup
+        ;;
+    "apt-get")
+        echo "Cleaning up..."
+        sudo apt-get autoremove -y && sudo apt-get clean
+        ;;
+    "yum")
+        echo "Cleaning up..."
+        sudo yum clean all
+        ;;
+    esac
+}
+
+# Function to install a single dependency
+install_dependency() {
+    local package_manager=$1
+    local dependency=$2
+    case $package_manager in
+    "brew")
+        brew install "$dependency"
+        ;;
+    "apt-get")
+        sudo apt-get install -y "$dependency"
+        ;;
+    "yum")
+        sudo yum install -y "$dependency"
+        ;;
+    esac
+}
+
 # Function to install dependencies based on the package manager
 install_dependencies() {
     local package_manager=$1
     shift
+
+    update_and_upgrade "$package_manager"
+
+    echo "Installing dependencies..."
     for dependency in "$@"; do
-        case $package_manager in
-            "brew") brew install "$dependency" ;;
-            "apt-get") sudo apt-get install -y "$dependency" ;;
-            "yum") sudo yum install -y "$dependency" ;;
-            *) echo "Unsupported package manager: $package_manager"; exit 1 ;;
-        esac
+        echo "Installing $dependency..."
+        install_dependency "$package_manager" "$dependency"
         INSTALLED_DEPENDENCIES+=("$dependency ($package_manager)")
     done
+
+    cleanup "$package_manager"
 }
 
 # Function to install dependencies from a list
 install_dependency_list() {
     local package_manager=$1
     local dependencies_file=$2
+
+    update_and_upgrade "$package_manager"
+
+    echo "Installing dependencies from list..."
     while IFS=, read -r dependency link_or_path; do
         if [ -n "$link_or_path" ]; then
+            echo "Installing $dependency from $link_or_path"
             if [[ "$link_or_path" =~ ^http ]]; then
-                echo "Installing $dependency from $link_or_path"
                 case $package_manager in
-                    "brew") brew install "$link_or_path" ;;
-                    "apt-get") wget "$link_or_path" -O /tmp/"$dependency".deb && sudo dpkg -i /tmp/"$dependency".deb ;;
-                    "yum") wget "$link_or_path" -O /tmp/"$dependency".rpm && sudo yum localinstall -y /tmp/"$dependency".rpm ;;
+                "brew") brew install "$link_or_path" ;;
+                "apt-get") wget "$link_or_path" -O /tmp/"$dependency".deb && sudo dpkg -i /tmp/"$dependency".deb ;;
+                "yum") wget "$link_or_path" -O /tmp/"$dependency".rpm && sudo yum localinstall -y /tmp/"$dependency".rpm ;;
                 esac
             else
-                echo "Installing $dependency from local path $link_or_path"
                 case $package_manager in
-                    "brew") brew install "$link_or_path" ;;
-                    "apt-get") sudo dpkg -i "$link_or_path" ;;
-                    "yum") sudo yum localinstall -y "$link_or_path" ;;
+                "brew") brew install "$link_or_path" ;;
+                "apt-get") sudo dpkg -i "$link_or_path" ;;
+                "yum") sudo yum localinstall -y "$link_or_path" ;;
                 esac
             fi
         else
             echo "Installing $dependency from default repository"
-            install_dependencies "$package_manager" "$dependency"
+            install_dependency "$package_manager" "$dependency"
         fi
         INSTALLED_DEPENDENCIES+=("$dependency ($package_manager)")
-    done < "$dependencies_file"
+    done <"$dependencies_file"
+
+    cleanup "$package_manager"
 }
 
 # Function to determine the package manager and set it globally
@@ -103,9 +169,9 @@ install_essential_tools() {
 # Function to install programming languages
 install_programming_languages() {
     case $PACKAGE_MANAGER in
-        "brew") install_dependencies "$PACKAGE_MANAGER" go python ;;
-        "apt-get") install_dependencies "$PACKAGE_MANAGER" golang python3 python3-pip ;;
-        "yum") install_dependencies "$PACKAGE_MANAGER" golang python3 python3-pip ;;
+    "brew") install_dependencies "$PACKAGE_MANAGER" go python ;;
+    "apt-get") install_dependencies "$PACKAGE_MANAGER" golang python3 python3-pip ;;
+    "yum") install_dependencies "$PACKAGE_MANAGER" golang python3 python3-pip ;;
     esac
 }
 
@@ -113,7 +179,7 @@ install_programming_languages() {
 install_meslolgs_nerd_font() {
     if [ ! -f "$HOME/.local/share/fonts/MesloLGS NF Regular.tff" ]; then
         mkdir -p ~/.local/share/fonts
-        cd ~/.local/share/fonts
+        cd ~/.local/share/fonts || return
         curl -fLo "MesloLGS NF Regular.ttf" https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip
         unzip Meslo.zip -d meslo
         mv meslo/*.ttf ~/.local/share/fonts/
@@ -132,13 +198,14 @@ show_installed_dependencies() {
 
 # Function to start shell
 start_shell() {
-    if command -v zsh &> /dev/null; then
+    if command -v zsh &>/dev/null; then
         zsh
-    elif command -v bash &> /dev/null; then
+    elif command -v bash &>/dev/null; then
         bash
     else
         echo "Neither zsh nor bash is installed. Please install one of them manually."
-    fi}
+    fi
+}
 
 # Default values for flags
 ENABLE_AUTO_UPDATE=true
@@ -149,9 +216,18 @@ INSTALLED_DEPENDENCIES=()
 # Parse command-line arguments
 while [[ "$#" -gt 0 ]]; do
     case $1 in
-        -a|--disable-auto-update) ENABLE_AUTO_UPDATE=false; shift ;;
-        -d|--dependencies) DEPENDENCIES_FILE="$2"; shift 2 ;;
-        *) ADDITIONAL_DEPENDENCIES+=("$1"); shift ;;
+    -a | --disable-auto-update)
+        ENABLE_AUTO_UPDATE=false
+        shift
+        ;;
+    -d | --dependencies)
+        DEPENDENCIES_FILE="$2"
+        shift 2
+        ;;
+    *)
+        ADDITIONAL_DEPENDENCIES+=("$1")
+        shift
+        ;;
     esac
 done
 
diff --git a/scripts/update_brew_lists b/scripts/update_brew_lists
--- a/scripts/update_brew_lists
+++ b/scripts/update_brew_lists
@@ -2,32 +2,31 @@
 
 BREW_PREFIX="/usr/local/bin/"
 BREW_LIST_DIR="$HOME/.local/bin/.brew_lists"
-CASK_LIST_DIR="$HOME/.local/bin/.brew_lists"
 BREW_LIST="$BREW_LIST_DIR/brew_list.txt"
-CASK_LIST="$CASK_LIST_DIR/cask_list.txt"
+CASK_LIST="$BREW_LIST_DIR/cask_list.txt"
 NEW_BREW_LIST="$BREW_LIST_DIR/brew_list.txt.new"
-NEW_CASK_LIST="$CASK_LIST_DIR/cask_list.txt.new"
+NEW_CASK_LIST="$BREW_LIST_DIR/cask_list.txt.new"
 
 # Function to check if the lists are different
 are_lists_different() {
-    diff -q "$1" "$2" &> /dev/null
+    diff -q "$1" "$2" &>/dev/null
 }
 
 # Function to update the brew and cask lists
 update_lists() {
     echo "Updating brew list..."
-    "$BREW_PREFIX"brew list > "$NEW_BREW_LIST"
+    "$BREW_PREFIX"brew list --formula >"$NEW_BREW_LIST"
     chmod 664 "$NEW_BREW_LIST"
 
     echo "Updating cask list..."
-    "$BREW_PREFIX"brew list --cask > "$NEW_CASK_LIST"
+    "$BREW_PREFIX"brew list --cask >"$NEW_CASK_LIST"
     chmod 664 "$NEW_CASK_LIST"
 }
 
 # Function to install Homebrew and packages
 install_packages() {
     # Install Homebrew if not installed
-    if ! command -v "$BREW_PREFIX"brew &> /dev/null; then
+    if ! command -v "$BREW_PREFIX"brew &>/dev/null; then
         echo "Installing Homebrew..."
         /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
     fi
@@ -35,14 +34,14 @@ install_packages() {
     # Install brew packages
     if [ -s "$BREW_LIST" ]; then
         echo "Installing brew packages..."
-        xargs "$BREW_PREFIX"brew install < "$BREW_LIST"
+        xargs "$BREW_PREFIX"brew install <"$BREW_LIST"
         echo "Brew packages installed successfully."
     fi
 
     # Install cask packages
     if [ -s "$CASK_LIST" ]; then
         echo "Installing cask packages..."
-        xargs "$BREW_PREFIX"brew install --cask < "$CASK_LIST"
+        xargs "$BREW_PREFIX"brew install --cask <"$CASK_LIST"
         echo "Cask packages installed successfully."
     fi
 }
@@ -60,7 +59,7 @@ save_lists() {
 # Function to commit changes to Git
 commit_to_git() {
     current_dir=$PWD
-    cd $HOME/.local/bin || exit
+    cd "$HOME"/.local/bin || exit
     git pull
     git add "$BREW_LIST" "$CASK_LIST"
     git commit -m "Update brew lists"
@@ -71,22 +70,22 @@ commit_to_git() {
 # Check command-line arguments
 while [[ $# -gt 0 ]]; do
     case "$1" in
-        --install)
-            install_packages
-            exit 0
-            ;;
-        --save-brew-dir)
-            shift
-            "$BREW_PREFIX"brew autoupdate start
-            ;;
-        --save-cask-dir)
-            shift
-            CASK_LIST_DIR="$1"
-            ;;
-        *)
-            echo "Invalid argument: $1"
-            exit 1
-            ;;
+    --install)
+        install_packages
+        exit 0
+        ;;
+    --save-brew-dir)
+        shift
+        "$BREW_PREFIX"brew autoupdate start
+        ;;
+    --save-cask-dir)
+        shift
+        CASK_LIST_DIR="$1"
+        ;;
+    *)
+        echo "Invalid argument: $1"
+        exit 1
+        ;;
     esac
     shift
 done
diff --git a/scripts/volumizer b/scripts/volumizer
--- a/scripts/volumizer
+++ b/scripts/volumizer
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 
-APP_NAME="Volumizer"
 MAX_VOLUME=50
 ONLY_ON_HEADPHONES=false
 NOTIFICATION_TITLE="Volume Limiter"
@@ -27,12 +26,12 @@ display_notification_macos() {
         local last_notification
         last_notification=$(cat "$notification_file")
         if [[ "$last_notification" == "$subtitle" ]]; then
-            return 0  # Notification already displayed
+            return 0 # Notification already displayed
         fi
     fi
 
     osascript -e "display notification \"$subtitle\" with title \"$title\""
-    echo "$subtitle" > "$notification_file"
+    echo "$subtitle" >"$notification_file"
 }
 
 # Function to check if output is on internal speakers on macOS
@@ -68,12 +67,12 @@ display_notification_linux() {
         local last_notification
         last_notification=$(cat "$notification_file")
         if [[ "$last_notification" == "$subtitle" ]]; then
-            return 0  # Notification already displayed
+            return 0 # Notification already displayed
         fi
     fi
 
     notify-send "$title" "$subtitle"
-    echo "$subtitle" > "$notification_file"
+    echo "$subtitle" >"$notification_file"
 }
 
 # Function to check if output is on internal speakers on Linux
@@ -92,7 +91,7 @@ check_headphones() {
         else
             if [ "$HEADPHONES_CONNECTED" = false ]; then
                 HEADPHONES_CONNECTED=true
-                $limit_volume
+                limit_volume
                 $display_notification "$NOTIFICATION_TITLE" "Limiting your 🎧 headphones to $MAX_VOLUME% to protect your ears"
             fi
         fi
@@ -132,39 +131,39 @@ fi
 # Parse command-line arguments
 while [[ $# -gt 0 ]]; do
     case "$1" in
-        --headphones-only)
-            ONLY_ON_HEADPHONES=true
-            shift
-            ;;
-        --max-volume)
-            if [[ "$2" =~ ^[0-9]+$ && "$2" -ge 0 && "$2" -le 100 ]]; then
-                MAX_VOLUME="$2"
-                shift 2
-            else
-                echo "Error: --max-volume must be followed by a valid percentage (0-100)."
-                exit 1
-            fi
-            ;;
-        --delay)
-            if [[ "$2" =~ ^[0-9]+$ && "$2" -gt 0 ]]; then
-                DELAY="$2"
-                shift 2
-            else
-                echo "Error: --delay must be followed by a valid positive integer."
-                exit 1
-            fi
-            ;;
-        *)
-            echo "Usage: $0 [--headphones-only] [--max-volume <percentage>] [--delay <seconds>] [--macos | --linux]"
+    --headphones-only)
+        ONLY_ON_HEADPHONES=true
+        shift
+        ;;
+    --max-volume)
+        if [[ "$2" =~ ^[0-9]+$ && "$2" -ge 0 && "$2" -le 100 ]]; then
+            MAX_VOLUME="$2"
+            shift 2
+        else
+            echo "Error: --max-volume must be followed by a valid percentage (0-100)."
             exit 1
-            ;;
+        fi
+        ;;
+    --delay)
+        if [[ "$2" =~ ^[0-9]+$ && "$2" -gt 0 ]]; then
+            DELAY="$2"
+            shift 2
+        else
+            echo "Error: --delay must be followed by a valid positive integer."
+            exit 1
+        fi
+        ;;
+    *)
+        echo "Usage: $0 [--headphones-only] [--max-volume <percentage>] [--delay <seconds>] [--macos | --linux]"
+        exit 1
+        ;;
     esac
 done
 
-for (( i=1; i<=$((60/DELAY)); i++ )); do
+for ((i = 1; i <= $((60 / DELAY)); i++)); do
     check_headphones
     limit_volume
 
-    sleep $DELAY
+    sleep "$DELAY"
 done
 
