changes to scripts

diff --git a/scripts/setup_dev_env b/scripts/setup_dev_env
--- a/scripts/setup_dev_env
+++ b/scripts/setup_dev_env
@@ -133,7 +133,7 @@ set_package_manager() {
             exit 1
         fi
     else
-        echo "Unsupported operating system. Exiting."
+        echo "Unsupported operating system $(uname). Exiting."
         exit 1
     fi
 }
@@ -141,7 +141,9 @@ set_package_manager() {
 # Function to handle auto-updates for Homebrew
 handle_auto_update() {
     if [ "$ENABLE_AUTO_UPDATE" == true ] && [ "$PACKAGE_MANAGER" == "brew" ]; then
-        brew autoupdate --start --upgrade --cleanup
+        if command_exists brew; then
+            brew autoupdate --start --upgrade --cleanup
+        fi
     fi
 }
 
@@ -149,15 +151,26 @@ handle_auto_update() {
 install_and_configure_shell() {
     if ! command_exists zsh; then
         install_dependencies "$PACKAGE_MANAGER" zsh
-        if [ ! -d "$HOME/.oh-my-zsh" ]; then
-            git clone https://github.com/ohmyzsh/ohmyzsh.git "$HOME/.oh-my-zsh"
+        # Replaced by zinit in .zshrc
+        # if [ ! -d "$HOME/.oh-my-zsh" ]; then
+        #     git clone https://github.com/ohmyzsh/ohmyzsh.git "$HOME/.oh-my-zsh"
+        # fi
+        if [ "$SHELL" != "$(command -v zsh)" ]; then
+            chsh -s "$(command -v zsh)"
         fi
-        chsh -s "$(command -v zsh)"
+
+        exec zsh -l
     fi
 }
 
 # Function to install essential tools
 install_essential_tools() {
+    if ! command_exists curl; then
+        install_dependencies "$PACKAGE_MANAGER" curl
+    fi
+    if ! command_exists unzip; then
+        install_dependencies "$PACKAGE_MANAGER" unzip
+    fi
     if ! command_exists git; then
         install_dependencies "$PACKAGE_MANAGER" git fd ripgrep fzf tree
     fi
@@ -166,18 +179,80 @@ install_essential_tools() {
     fi
 }
 
-# Function to install programming languages
-install_programming_languages() {
+# Function to install Go
+install_go() {
     case $PACKAGE_MANAGER in
-    "brew") install_dependencies "$PACKAGE_MANAGER" go python ;;
-    "apt-get") install_dependencies "$PACKAGE_MANAGER" golang python3 python3-pip ;;
-    "yum") install_dependencies "$PACKAGE_MANAGER" golang python3 python3-pip ;;
+    "brew") install_dependencies "$PACKAGE_MANAGER" go ;;
+    "apt-get" | "yum") install_dependencies "$PACKAGE_MANAGER" golang ;;
+    *)
+        echo "Unsupported package manager: $PACKAGE_MANAGER"
+        exit 1
+        ;;
     esac
+}
+
+# Function to install Python and Poetry
+install_python() {
+    # Check if "global" argument is passed
+    GLOBAL_INSTALL=true
+    if [[ "$1" == "local" ]]; then
+        GLOBAL_INSTALL=false
+    fi
+
+    # Install pyenv if it's not already installed
+    if ! command -v pyenv >/dev/null 2>&1; then
+        echo "Installing pyenv..."
+        curl https://pyenv.run | bash
+
+        # Set up pyenv in the current shell session
+        export PATH="$HOME/.pyenv/bin:$PATH"
+        eval "$(pyenv init --path)"
+        eval "$(pyenv init -)"
+        eval "$(pyenv virtualenv-init -)"
+    fi
+
+    # Ensure Python 3.7+ is installed via pyenv
+    REQUIRED_VERSION="3.7.0"
+    # Function to check if the installed Python version is at least the required version
+    check_python_version() {
+        INSTALLED_VERSION=$(python -c "import sys; print('{}.{}'.format(sys.version_info.major, sys.version_info.minor))")
+
+        if [[ $(printf '%s\n' "$REQUIRED_VERSION" "$INSTALLED_VERSION" | sort -V | head -n 1) == "$REQUIRED_VERSION" ]]; then
+            echo "Python version $INSTALLED_VERSION is installed and meets the requirement."
+        else
+            echo "Python version is less than $REQUIRED_VERSION. Exiting."
+            exit 1
+        fi
+    }
+
+    check_python_version
+
+    # Set Python version globally or locally
+    if [[ "$GLOBAL_INSTALL" == true ]]; then
+        echo "Setting Python $REQUIRED_VERSION as the global version..."
+        pyenv global "$REQUIRED_VERSION"
+    else
+        echo "Setting Python $REQUIRED_VERSION as the local version..."
+        pyenv local "$REQUIRED_VERSION"
+    fi
+
+    # Rehash pyenv to make the new version available
+    pyenv rehash
+
+    # Install Poetry using the pyenv-installed Python
+    echo "Installing Poetry..."
+    curl -sSL https://install.python-poetry.org | python3 -
+}
+
+# Function to install all programming languages
+install_programming_languages() {
+    install_go
+    install_python global # Pass "global" as an argument to set Python globally
 }
 
 # Function to install MesloLGS Nerd Font
 install_meslolgs_nerd_font() {
-    if [ ! -f "$HOME/.local/share/fonts/MesloLGS NF Regular.tff" ]; then
+    if [ ! -f "$HOME/.local/share/fonts/MesloLGS NF Regular.ttf" ]; then
         mkdir -p ~/.local/share/fonts
         cd ~/.local/share/fonts || return
         curl -fLo "MesloLGS NF Regular.ttf" https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip
@@ -202,6 +277,8 @@ start_shell() {
         zsh
     elif command -v bash &>/dev/null; then
         bash
+    elif command -v fish &>/dev/null; then
+        fish
     else
         echo "Neither zsh nor bash is installed. Please install one of them manually."
     fi
@@ -253,4 +330,3 @@ fi
 
 show_installed_dependencies
 start_shell
-
